### ISSUE TITLE
Twig \ Error \ LoaderError Webpack css entry default not exists.

### ISSUE THREAD

**Issue by markjcorrigan** [darkalchemy/Slim-Auth#30]
[
![web manifest file not exist](https://github.com/darkalchemy/Slim-Auth/assets/36232130/3352d055-b778-4275-868f-f10e87ed0ede)
]([2024-02-09T08_09_14_735Z-debug-0.log](https://github.com/darkalchemy/Slim-Auth/files/14219252/2024-02-09T08_09_14_735Z-debug-0.log))
Hi I have spent hours trying to get your framework to work.
This is the error:  Twig \ Error \ LoaderError
Webpack css entry default not exists.

and this is the page / problem I see in Whoops!  Please can you assist me.

C:\xampp\htdocs\slimdark\resources\views\layouts\app.twig
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{{ settings.site_name }}</title>
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/site.webmanifest">
    {% block css %}
        {% webpack_entry_css 'default' %}
    {% endblock %}
</head>
<body>
<section class="hero is-fullheight">
    {% include 'components/menu.twig' %}
 
    {% block content %}{% endblock %}
 
    {% include 'components/footer.twig' %}
    {% block js %}
        {% webpack_entry_js 'default' %}
    {% endblock %}
 
    {% include 'components/cookieconsent.twig' %}
</section>
</body>
</html>
 
Arguments
"Webpack css entry default not exists."

BELOW IS THE TAIL END OF THE INSTALL COMMAND FROM YOUR INSTRUCTIONS:  I.E. composer create-project darkalchemy/slim-auth

 - Installing filp/whoops (2.15.4): Extracting archive
  - Installing zeuxisoo/slim-whoops (0.7.3): Extracting archive
38 package suggestions were added by new dependencies, use `composer suggest` to see details.
Package swiftmailer/swiftmailer is abandoned, you should avoid using it. Use symfony/mailer instead.
Generating autoload files
56 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
> composer dump-autoload -o
Generating optimized autoload files
Generated optimized autoload files containing 2827 classes
No security vulnerability advisories found.
> php -r "copy('config/settings.example.php', 'config/settings.php');"
> npm install
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! code 1
npm ERR! path C:\xampp\htdocs\slimdarksecond\slim-auth\node_modules\node-sass
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node scripts/build.js
npm ERR! Building: C:\Program Files\nodejs\node.exe C:\xampp\htdocs\slimdarksecond\slim-auth\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
npm ERR! gyp verb cli   'C:\\xampp\\htdocs\\slimdarksecond\\slim-auth\\node_modules\\node-gyp\\bin\\node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@8.4.1
npm ERR! gyp info using node@20.11.0 | win32 | x64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb find Python Python is not set from command line or npm configuration
npm ERR! gyp verb find Python Python is not set from environment variable PYTHON
npm ERR! gyp verb find Python checking if "python3" can be used
npm ERR! gyp verb find Python - executing "python3" to get executable path
npm ERR! gyp verb find Python - "python3" is not in PATH or produced an error
npm ERR! gyp verb find Python checking if "python" can be used
npm ERR! gyp verb find Python - executing "python" to get executable path
npm ERR! gyp verb find Python - executable path is "C:\Python312\python.exe"
npm ERR! gyp verb find Python - executing "C:\Python312\python.exe" to get version
npm ERR! gyp verb find Python - version is "3.12.2"
npm ERR! gyp info find Python using Python version 3.12.2 found at "C:\Python312\python.exe"
npm ERR! gyp verb get node dir no --target version specified, falling back to host node version: 20.11.0
npm ERR! gyp verb command install [ '20.11.0' ]
npm ERR! gyp verb install input version string "20.11.0"
npm ERR! gyp verb install installing version: 20.11.0
npm ERR! gyp verb install --ensure was passed, so won't reinstall if already installed
npm ERR! gyp verb install version is already installed, need to check "installVersion"
npm ERR! gyp verb got "installVersion" 9
npm ERR! gyp verb needs "installVersion" 9
npm ERR! gyp verb install version is good
npm ERR! gyp verb get node dir target node version installed: 20.11.0
npm ERR! gyp verb build dir attempting to create "build" dir: C:\xampp\htdocs\slimdarksecond\slim-auth\node_modules\node-sass\build
npm ERR! gyp verb build dir "build" dir needed to be created? Yes
npm ERR! gyp verb find VS msvs_version not set from command line or npm config
npm ERR! gyp verb find VS VCINSTALLDIR not set, not running in VS Command Prompt
npm ERR! gyp verb find VS could not use PowerShell to find Visual Studio 2017 or newer, try re-running with '--loglevel silly' for more details
npm ERR! gyp verb find VS looking for Visual Studio 2015
npm ERR! gyp verb find VS - not found
npm ERR! gyp verb find VS not looking for VS2013 as it is only supported up to Node.js 8
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! find VS msvs_version not set from command line or npm config
npm ERR! gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
npm ERR! gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer, try re-running with '--loglevel silly' for more details
npm ERR! gyp ERR! find VS looking for Visual Studio 2015
npm ERR! gyp ERR! find VS - not found
npm ERR! gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! find VS **************************************************************
npm ERR! gyp ERR! find VS You need to install the latest version of Visual Studio
npm ERR! gyp ERR! find VS including the "Desktop development with C++" workload.
npm ERR! gyp ERR! find VS For more information consult the documentation at:
npm ERR! gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
npm ERR! gyp ERR! find VS **************************************************************
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Could not find any Visual Studio installation to use
npm ERR! gyp ERR! stack     at VisualStudioFinder.fail (C:\xampp\htdocs\slimdarksecond\slim-auth\node_modules\node-gyp\lib\find-visualstudio.js:122:47)
npm ERR! gyp ERR! stack     at C:\xampp\htdocs\slimdarksecond\slim-auth\node_modules\node-gyp\lib\find-visualstudio.js:75:16
npm ERR! gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\xampp\htdocs\slimdarksecond\slim-auth\node_modules\node-gyp\lib\find-visualstudio.js:363:14)
npm ERR! gyp ERR! stack     at C:\xampp\htdocs\slimdarksecond\slim-auth\node_modules\node-gyp\lib\find-visualstudio.js:71:14
npm ERR! gyp ERR! stack     at C:\xampp\htdocs\slimdarksecond\slim-auth\node_modules\node-gyp\lib\find-visualstudio.js:384:16
npm ERR! gyp ERR! stack     at C:\xampp\htdocs\slimdarksecond\slim-auth\node_modules\node-gyp\lib\util.js:54:7
npm ERR! gyp ERR! stack     at C:\xampp\htdocs\slimdarksecond\slim-auth\node_modules\node-gyp\lib\util.js:33:16
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:430:5)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:518:28)
npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1105:16)
npm ERR! gyp ERR! System Windows_NT 10.0.19045
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\xampp\\htdocs\\slimdarksecond\\slim-auth\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd C:\xampp\htdocs\slimdarksecond\slim-auth\node_modules\node-sass
npm ERR! gyp ERR! node -v v20.11.0
npm ERR! gyp ERR! node-gyp -v v8.4.1
npm ERR! gyp ERR! not ok
npm ERR! Build failed with error code: 1

npm ERR! A complete log of this run can be found in: C:\Users\Markus\AppData\Local\npm-cache\_logs\2024-02-09T08_00_13_275Z-debug-0.log
Script npm install handling the post-create-project-cmd event returned with error code 1

**Comment by markjcorrigan** [comment]
Regarding above I have added the error log if that can help you to pin down the issue.   I am really excited to get a slim 4 solution that includes Sentinel  I am frustrated that I cannot get your solution to work.  Would it not be possible to put into place a basic twig template based framework with login page, dashboard, signup etc. without all the nonsense that goes with node.  It just seems to me that I always have problems with node and it never gets better.  I know that I did a course with CodeCourse.com on slim auth and it had such a frontend simply put together.  It also seems to be much in line with the work you have done but it is dates and keeps running into dependency issues.
[2024-02-09T08_09_14_735Z-debug-0.log](https://github.com/darkalchemy/Slim-Auth/files/14219297/2024-02-09T08_09_14_735Z-debug-0.log)

**Comment by darkalchemy** [comment]
Well, this code hasn't been updated in a couple of years. Without going through it all and making updates and changes,  I doubt it will work as it's now.

I had planned to rewrite it, replacing several things,  but I've never had the ti.e.

**Comment by markjcorrigan** [comment]
Hi there. 

Thanks for getting back to me. 

I am not sure if you have looked at the 3 books from Daniel Opitz on Slim 4. See attached. 
The only thing I see that is missing there is adding in Sentinel func. 
Everything else seems to be working great. 

It would be awesome if you could consider his baseline (Slim 4 skeleton) and then incorporate Sentinel. 
Even though I quickly managed to use Daniel's code to get basic stuff done, including basic authentication, pulling in Sentinel would be a massive challenge for me. 
Possibly you can leverage off his base and build it? 

I banged my head for about 8 hours trying to get the views to work but I did not have any luck as I kept getting the error I showed you. 
I have managed to get your application to return slim views I incorporated from "codecourse.com", Alex's setup for his authentication application course. 
But, for some reason I cannot get access to my database and I keep getting validation errors. 
I will give it a break now as I am bushed and continue on Monday. 
See attached. 

Kind regards. 

Mark Corrigan 
Cell: 082 803 2304 
[ https://www.pmway.co.za/cv/index.html | Portfolio ]

**Comment by darkalchemy** [comment]
TBH, if I was to update this, I would replace Sentinel with PhpAuth. But, I don't see having the time to work on this anytime soon.

My apologies for your wasted time.

**Comment by markjcorrigan** [comment]
May I ask you a question. 
Is there a way to "bypass" the composer.json settings and config. 
All I want to do is understand Slim 4 and how it works with Sentinel. 
I.e. I would be happy with the most basic CSS and limited javascript. 
I am just trying to get at the knowledge of how containers work and how to correctly set up Sentinel in Slim 4 so it works with PHP 8+. 
Possibly this is too big a goal for someone who is still trying to learn his way. 
I do now see that trying to use the other twig views I talk about below will not work as much of the logic is built into your views. 
I am sure there is a lot else I am missing. 
Sadly there are no good courses I can follow showing how to do all of this and the course codecourse.com offer keeps giving me dependency problems, as do other repos I try. 
Frustrating. 

Regards. 

Mark Corrigan 
Cell: 082 803 2304 
[ https://www.pmway.co.za/cv/index.html | Portfolio ]

**Comment by markjcorrigan** [comment]
Hi there. 
No problem. 
I learned a lot. 
If you recommend PHPAuth I will definitely look into this. 

Mark Corrigan 
Cell: 082 803 2304 
[ https://www.pmway.co.za/cv/index.html | Portfolio ]

**Comment by darkalchemy** [comment]
I would offer that Daniel has a better grasp of this than I do. Much better.  There are so many issues with this code, it would be simpler to start from scratch. 

I learned a lot while writing this and was in the process of fixing some of the issues that I saw. But, rl pulled me away and i simply lost interest.

**Comment by markjcorrigan** [comment]
Thank you.I really appreciate your feedback.Kind regards.Mark.Sent from my Galaxy
-------- Original message --------From: darkalchemy ***@***.***> Date: 2024/02/09  15:30  (GMT+02:00) To: darkalchemy/Slim-Auth ***@***.***> Cc: Mark Corrigan ***@***.***>, Author ***@***.***> Subject: Re: [darkalchemy/Slim-Auth] Twig \ Error \ LoaderError Webpack css entry default not exists. (Issue #30) 
I would offer that Daniel has a better grasp off this than I do. Much better.  There are so many issues with this code, it would be simpler to start from scratch.
I learned a lot while writing this and was in the process of fixing some of the issues that I saw. But, rl pulled me away and i simply lost interest.

**Comment by darkalchemy** [comment]
This should be fixed in e2bff5c.

<img width="1345" height="651" alt="Image" src="https://github.com/user-attachments/assets/b6becf6d-03c7-4b88-85d0-c2d745c583ed" />

<img width="1345" height="646" alt="Image" src="https://github.com/user-attachments/assets/cbd46eca-c60a-4d3e-b961-2fb37c96e3a6" />

<img width="1341" height="652" alt="Image" src="https://github.com/user-attachments/assets/58122aa6-9916-4703-9289-c922eca37793" />

<img width="1346" height="649" alt="Image" src="https://github.com/user-attachments/assets/cf357e8e-9b7e-4107-ab9c-83409d7cb730" />
